### ISSUE TITLE
Build fails to place JCL member in PROCLIB

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-smpe-packaging#17]
The build specifies the location for the PROCLIB memer as `BLD.AZWE001.BLD.PROCLIB` but this dataset is not found, so the copy fails.  If you create `BLD.AZWE001.BLD.PROCLIB` beforehand, the build deletes it.

![image](https://user-images.githubusercontent.com/36740892/63281331-6071b300-c2a4-11e9-8b6f-f0ace0f8caab.png)

So that dataset needs to be created somewhere.

**Comment by John-A-Davies** [comment]
I created `BLD.AZWE001.BLD.PROCLIB` with ISPF during build #27 and then the build correctly placed member ZOWESVR in that dataset and also in `/zaas1/zowe-smpe-packaging-20190820092654/zowe/AZWE001/mvs/PROCLIB`.  

The build still failed with
```
** ERROR smpe-split.sh not all files are moved to /zaas1/zowe-smpe-packaging-20190820092654/zowe/AZWE001/split
ZOWESVR.JCL
```

**Comment by John-A-Davies** [comment]
FWIW, the ZOWESVR JCL file is already shipped as `scripts/templates/ZOWESVR.template.jcl` in ZWEPAX17.

**Comment by John-A-Davies** [comment]
I fixed `smpe/bld/smpe-install.sh` to create the PROCLIB, which worked, so the
`PROC ZOWESVR placed in BLD.AZWE001.BLD.PROCLIB` works, and to delete `ZOWESVR.JCL`, which also worked, so `verifying split action` succeeds.  
I also fixed `smpe/bld/SMPMCS.txt` to contain ZWEPAX files 21 and 22, so you should not get 
`ERROR SMPMCS does not match list of actual parts`.

**Comment by John-A-Davies** [comment]
These fixes all worked but the build timed out after this command:
`cp /zaas1/zowe-smpe-packaging-20190820162133/zowe/AZWE001/BLD/ZWEPAX06 //'BLD.AZWE001.ZOWE.AZWE001.F4(ZWEPAX06)' 2>&1`

**Comment by John-A-Davies** [comment]
A build has now successfully completed
```
    Jenkins
    zowe-smpe-packaging
    Pull Requests (1)
    PR-18
    #7
```
It still says `Unable to create the PROCLIB member` but that did not cause the build to fail.  I will fix that issue and re-run.

**Comment by John-A-Davies** [comment]
```

[Pipeline] artifactoryUpload
[consumer_0] Deploying artifact: https://gizaartifactory.jfrog.io/gizaartifactory/libs-snapshot-local/org/zowe/smpe/1.4.0-PR-18/AZWE001-1.4.0-pr-18-7-20190821103240.pax.Z
[consumer_1] Deploying artifact: https://gizaartifactory.jfrog.io/gizaartifactory/libs-snapshot-local/org/zowe/smpe/1.4.0-PR-18/AZWE001.readme-1.4.0-pr-18-7-20190821103240.txt
```

**Comment by John-A-Davies** [comment]
I tested `AZWE001-1.4.0-pr-18-7-20190821103240.pax.Z` and all the SMP/E jobs ran RC=00.

The build `
    Jenkins
    zowe-smpe-packaging
    Pull Requests (1)
    PR-18
    #11
`
succeeded with `PROC ZOWESVR placed in BLD.AZWE001.BLD.PROCLIB`

To make it run cleanly, I created `BLD.AZWE001.BLD.PROCLIB` before the convenience install, and deleted it right afterwards, to avoid it being sucked into the SMP/E build SMPMCS.

**Comment by stevenhorsman** [comment]
Fixed by https://github.com/zowe/zowe-smpe-packaging/pull/20
