### ISSUE TITLE
Deliver initial FMID and PTFs on IBM Shop Z

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-smpe-packaging#26]
This epic is to track all the steps required such that the FMID and PTFs can be distributed on IBM Shop Z for extender products to be able to pre-requisite.

This is vendor neutral so can also be used by other vendor distribution channels

1.  Do we need to deliver the program directory in bookmaster format ?
2. If we switch the JCL to the substitution variable mechanism will that fail shop Z validation ?

**Comment by mpanch59** [comment]
Hi @OnnoVdT ,@John-A-Davies  and @Joe-Winchester 

have attached the ppt that was discussed on scrum on Wednesday 
[Service flow.pptx](https://github.com/zowe/zowe-smpe-packaging/files/3630820/Service.flow.pptx)

please review provide feedback and we can edit
